name: shreejikhakhra
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase Dependencies
  firebase_core: ^3.1.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.1

  # ðŸ“± App Packages
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  carousel_slider: ^5.1.1
  badges: ^3.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # ðŸ“¦ App Icon Generator
  flutter_launcher_icons: ^0.13.1

# ðŸš€ App Icon Configuration
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/SHREEJI_logo1.png"

# ðŸ“ Flutter Configuration
flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
